### ISSUE TITLE
TypeError: sequence item 0: expected string or Unicode, int found

### ISSUE THREAD

**Issue by RainSongg** [GTmac/HARP#4]
when I input 
python src/harp.py --input example_graphs/citeseer/citeseer.mat --model deepwalk --output citeseer.npy --sfdp-path bin/sfdp_linux,it throws following errors:
Number of nodes: 3312
Number of edges: 9072
Underlying network embedding model: deepwalk
{'scale': -1, 'num_paths': 40, 'path_length': 10, 'sg': 1, 'sfdp_path': 'bin/sfdp_linux', 'iter_count': 1, 'sample': 0.1, 'window_size': 10, 'lr_scheme': 'default', 'representation_size': 128, 'hs': 1, 'coarsening_scheme': 2, 'alpha': 0.025, 'min_alpha': 0.001}
Subgraph 1 with 2110 nodes and 7336 edges
Graph Coarsening...
Original graph with 2110 nodes and 7336 edges
Coarsening Round 1:
Generate coarsened graph with 1316 nodes and 4948 edges
Coarsening Round 2:
Generate coarsened graph with 867 nodes and 3386 edges
Coarsening Round 3:
Generate coarsened graph with 599 nodes and 2394 edges
Coarsening Round 4:
Generate coarsened graph with 426 nodes and 1790 edges
Coarsening Round 5:
Generate coarsened graph with 312 nodes and 1356 edges
Coarsening Round 6:
Generate coarsened graph with 178 nodes and 792 edges
Coarsening Round 7:
Generate coarsened graph with 108 nodes and 454 edges
Coarsening Round 8:
Generate coarsened graph with 71 nodes and 254 edges
Coarsening Round 9:
Generate coarsened graph with 53 nodes and 150 edges
Coarsening Round 10:
Generate coarsened graph with 36 nodes and 84 edges
Coarsening Round 11:
Generate coarsened graph with 27 nodes and 54 edges
Coarsening Round 12:
Generate coarsened graph with 19 nodes and 36 edges
Coarsening Round 13:
Generate coarsened graph with 13 nodes and 24 edges
Coarsening Round 14:
Generate coarsened graph with 9 nodes and 16 edges
Coarsening Round 15:
Generate coarsened graph with 6 nodes and 10 edges
Coarsening Round 16:
Generate coarsened graph with 4 nodes and 6 edges
{'window_size': 10, 'num_paths': 40, 'path_length': 10, 'sg': 1, 'iter': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'progress_threshold': 100000, 'sample': 0.1, 'scale': -1, 'lr_scheme': 'default', 'representation_size': 128, 'hs': 1, 'alpha': 0.025, 'report_loss': False, 'min_alpha': 0.001}
Start building Skip-gram + Hierarchical Softmax model on the coarsened graphs...
Training on graph level 16...
Traceback (most recent call last):
  File "src/harp.py", line 77, in <module>
    sys.exit(main())
  File "src/harp.py", line 62, in main
    lr_scheme='default',alpha=0.025,min_alpha=0.001,sg=1,hs=1,coarsening_scheme=2, sample=0.1)
  File "/home/rainsong/Desktop/HARP-master/src/graph_coarsening.py", line 312, in skipgram_coarsening_disconnected
    sample=sample)
  File "/home/rainsong/Desktop/HARP-master/src/graph_coarsening.py", line 385, in skipgram_coarsening_hs
    edges = build_deepwalk_corpus(recursive_graphs[level], num_paths, path_length, output)
  File "/home/rainsong/Desktop/HARP-master/src/graph_coarsening.py", line 542, in build_deepwalk_corpus
    num_workers=20)
  File "/usr/local/lib/python2.7/dist-packages/deepwalk-1.0.3-py2.7.egg/deepwalk/walks.py", line 85, in write_walks_to_disk
    for file_ in executor.map(_write_walks_to_disk, args_list):
  File "/home/rainsong/.local/lib/python2.7/site-packages/concurrent/futures/_base.py", line 641, in result_iterator
    yield fs.pop().result()
  File "/home/rainsong/.local/lib/python2.7/site-packages/concurrent/futures/_base.py", line 455, in result
    return self.__get_result()
  File "/home/rainsong/.local/lib/python2.7/site-packages/concurrent/futures/_base.py", line 414, in __get_result
    raise exception_type, self._exception, self._traceback
TypeError: sequence item 0: expected string or Unicode, int found
Is there someone can help me?

**Comment by RainSongg** [comment]
OK,I get it
the version of deepwalk in requirements.txt should less than 1.0.3,if use the newest version(1.0.3),it will report this error:)
